#!/bin/sh

set -e

. /etc/default/openmediavault
. /usr/share/openmediavault/scripts/helper-functions

SQL_MANAGEMENT_SITE_CONF="/etc/nginx/openmediavault-webgui.d/openmediavault-postgresql-management-site.conf"
SQL_MANAGEMENT_POOL_CONF="/etc/php5/fpm/pool.d/openmediavault-postgresql-management-site.conf"

case "$1" in
    purge)
        omv_config_delete "//services/postgresql"
    ;;

    remove)
        if [ -e "${SQL_MANAGEMENT_SITE_CONF}" ]; then
            rm ${SQL_MANAGEMENT_SITE_CONF}
        fi

        if [ -e "${SQL_MANAGEMENT_POOL_CONF}" ]; then
            rm ${SQL_MANAGEMENT_POOL_CONF}
        fi

        invoke-rc.d nginx reload
        invoke-rc.d php5-fpm reload
    ;;

    upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
    ;;

    *)
        echo "postrm called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

#DEBHELPER#

exit 0
