#!/bin/sh

set -e

. /etc/default/openmediavault
. /usr/share/openmediavault/scripts/helper-functions

SERVICE_XPATH_NAME="postgresql"
SERVICE_XPATH="/config/services/${SERVICE_XPATH_NAME}"

shared_folder_to_extra_options()
{
    data_sharedfolderref=$(omv_config_get "${SERVICE_XPATH}/data.sharedfolderref")
    data_directory="$(omv_get_sharedfolder_path "${data_sharedfolderref}")"
    extra_options=$(omv_config_get "${SERVICE_XPATH}/extra_options")

    # Delete unused sharedfolderref and showtab entries
    omv_config_delete "${SERVICE_XPATH}/data.sharedfolderref"
    omv_config_delete "${SERVICE_XPATH}/showtab"

    # Delete old extra_options and write new with datadir option
    omv_config_delete "${SERVICE_XPATH}/extra_options"

    # new line characters are not converted to new lines
    omv_config_add_element "${SERVICE_XPATH}" "extra_options" "data_directory = '${data_directory}'
${extra_options}"
}

case "$1" in
    configure)

        # Add the default configuration
        if ! omv_config_exists "${SERVICE_XPATH}"; then
            omv_config_add_element "/config/services" "${SERVICE_XPATH_NAME}"
            omv_config_add_element "${SERVICE_XPATH}" "enable" "0"
            omv_config_add_element "${SERVICE_XPATH}" "port" "5432"
            omv_config_add_element "${SERVICE_XPATH}" "bind_address" "localhost"
            omv_config_add_element "${SERVICE_XPATH}" "extra_options" ""
            omv_config_add_element "${SERVICE_XPATH}" "enable_management_site" "0"
        fi

        if dpkg --compare-versions "${2}" lt-nl "1.0.1"; then
            shared_folder_to_extra_options
        fi

        # Activate package triggers. These triggers are only set during the
        # package installation.
        dpkg-trigger update-fixperms
        dpkg-trigger update-locale
    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
        echo "postinst called with unknown argument" >&2
        exit 1
    ;;
esac

exit 0
